//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPC_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid ID { get; set; }
        public string FullName { get; set; }
        public short Age { get; set; }
        public string Email { get; set; }
        public string PW { get; set; }
        public byte[] Img { get; set; }
        public System.Guid RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
